site_name: yente
repo_url: https://github.com/opensanctions/yente

theme:
  name: material
  logo: https://assets.opensanctions.org/images/ura/logo_white.png
  favicon: https://assets.opensanctions.org/images/nura/favicon-32.png
  palette:
    primary: custom
    accent: custom
  custom_dir: docs/overrides
  features:
    - navigation.sections
extra_css: [stylesheets/extra.css]

extra:
  opensanctions_url: https://www.opensanctions.org
  opensanctions_api_url: https://api.opensanctions.org
  social:
    - icon: material/forum
      link: https://discuss.opensanctions.org/
    - icon: material/github
      link: https://github.com/opensanctions/rigour
    - icon: material/linkedin
      link: https://www.linkedin.com/company/opensanctions/
    - icon: material/web
      link: https://www.opensanctions.org

plugins:
  - search
  - autorefs
  - macros
  # - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false
          inventories:
            - http://rigour.followthemoney.tech/objects.inv
            - http://followthemoney.tech/objects.inv
  - redirects:
      redirect_maps:
        "docs/delivery.md": "delivery.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Troubleshooting: troubleshooting.md
  - Changelog: https://github.com/opensanctions/yente/releases
  - Deployment:
      - Overview: deploy/index.md
      - Upgrading: deploy/upgrading.md
      - Monitoring: deploy/monitoring.md
      - Restrictive firewalls: deploy/firewall.md
  - Configuration:
      - Settings: settings.md
      - OpenSanctions data: delivery.md
      - Data updates: reindex.md
      - Custom datasets: datasets.md
      - Search providers: opensearch.md

  - Toolchain:
      - followthemoney: https://followthemoney.tech/
      - rigour: https://rigour.followthemoney.tech/
      # - yente: https://yente.followthemoney.tech/
      - OpenAleph: https://openaleph.org/docs/
      - OpenSanctions: https://www.opensanctions.org/docs/
